# This is a basic workflow to help you get started with Actions

name: Postman API tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    #At the end of every day
    - cron: 5 * * * *
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - run: npm i
      
      #Install the newman cammand line utilyty and also install the thml extra reporter
      - name: Install newman
        run: |
          npm instal -g newman
          npm install -g newman-reporter-htmlextra
          npm install -g newman-reporter-testrail
          
      #Run the Postman collection
        -name: Run API Tests
        run: npm run postman
      
      
